#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys

# https://stackoverflow.com/a/45287769
mknod /dev/sda b 8 0 
mknod /dev/console c 5 1
mknod /dev/tty0 c 4 0
mknod /dev/tty1 c 4 1
mknod /dev/tty2 c 4 2
mknod /dev/tty3 c 4 3
mknod /dev/tty4 c 4 4
mknod /dev/tty5 c 4 5

mknod /dev/null c 1 3
mknod /dev/zero c 1 5
mknod /dev/random c 1 8
mknod /dev/urandom c 1 9
mknod /dev/ptmx c 5 2
mknod /dev/mem c 1 1

mknod /dev/watchdog c 10 130
mknod /dev/fb0 c 29 0

mkdir /dev/input
mknod /dev/input/mice c 13 63
mknod /dev/input/mouse0 c 13 32

#dd if=/dev/urandom of=/dev/fb0 count=1024 bs=1024


ip link set eth0 up
exec /bin/sh